# Generated by Django 2.2.6 on 2019-12-07 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_form_fill_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
