# Generated by Django 2.2.6 on 2019-12-08 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='reverse_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
