# Generated by Django 2.2.6 on 2019-11-06 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('ENG', 'English'), ('SPA', 'Spanish'), ('GER', 'German'), ('FRA', 'French'), ('ITA', 'Italian'), ('RUS', 'Russian')], max_length=3)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True, max_length=400)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('host_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_teacher', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
