# Generated by Django 2.2.6 on 2019-11-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0003_lesson_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
