# Generated by Django 2.2.6 on 2019-11-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0004_lesson_is_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reject_message',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
