# Generated by Django 2.2.6 on 2019-11-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0005_auto_20191117_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='form_fill_factor',
            field=models.FloatField(blank=True, default=1, max_length=4),
        ),
    ]
