# Generated by Django 2.2.6 on 2019-11-17 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0006_teacherprofile_form_fill_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
