# Generated by Django 2.2.6 on 2019-11-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0008_auto_20191121_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
