# Generated by Django 2.2.6 on 2019-12-08 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_teachers', '0009_auto_20191121_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='available', max_length=10)),
                ('s_time', models.TimeField(blank=True, null=True)),
                ('day', models.CharField(blank=True, default='available', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
