# Generated by Django 2.2.6 on 2019-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0011_auto_20191209_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='num_ratings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='rate_avg',
            field=models.FloatField(blank=True, default=1, max_length=4),
        ),
    ]
