# Generated by Django 2.2.6 on 2019-12-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0012_auto_20191209_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='rate_avg',
            field=models.FloatField(blank=True, max_length=4),
        ),
    ]
